  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo # yum.repos.d

 
  - name: install rabbitmq server
    ansible.builtin.package: #ansible module
      name: rabbitmq-server
      state: present

  - name: start and enable rabbitmq server
    ansible.builtin.service: #ansile  module 
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: create and provide permissions to user
    community.rabbitmq.rabbitmq_user: #community module #if not avialable we use command or shell
      user: roboshop
      password: roboshop123
      permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      state: present