- name: app setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: app-setup.yaml
- name: app setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: nodejs.yaml


- name: system setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: system-setup.yaml
    