- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml #chaniging yml to yml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yml #chaniging yml to yml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yml #chaniging yml to yml