- name: app setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: app-setup.yaml
- name: app setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: nodejs.yaml

#not common

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output

- name: load products into mongodb
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }}</app/db/master-data.js
  when: catalogue_output.stdout | int < 0


- name: app setup
  ansible.builtin.import_role:  #statically including a role in the playbook.
    name: common  #name of the role which i want to include
    tasks_from: system-setup.yaml