  - name: disbale dnf module #command module
    ansible.builtin.command: dnf module disable redis -y
    #when module is not available we use command if other features are not requored

  - name: enable redis 7 #command module 
    ansible.builtin.command: dnf module enable redis:7 -y 

  - name: install redis #package module
    ansible.builtin.package:
      name: redis
      state: present
#ansible replace a word
  - name: ansible replace a word #replace module
    ansible.builtin.replace:
      path: /etc/redis/redis.conf   #/etc/mongod.conf   not #momng.conf
      regexp: '127.0.0.1' #which pattern should replace
      replace:  '0.0.0.0'  # tihs has to be replaced   

  - name: update  peotected mode yes to no  (line)    #lineinfile #chcek once updated 0 or not
    ansible.builtin.lineinfile: #it is not a word it was line
      path: /etc/redis/redis.conf   #/etc/mongod.conf   not #momng.conf
      regexp: 'protected-mode' #which pattern should replace
      line: 'protected-mode no'  # tihs has to be replaced   

  - name: start and enable  redis services #service module
    ansible.builtin.service:
      name: redis
      state: started  #if service started if package present or latest
      enabled: Yes       #jdjd 
  

      